// Auto-generated by tools/mkcard.py. Do not edit: re-run it.
//
// What the card file holds and in what order, for a build with CARDIMAGES on. The layout
// is set out in tools/mkcard.py; this only names the entries so the game can ask for one
// by name and check that the card it found was made by this build.

#pragma once
#include <stdint.h>

//the file the game looks for in the card's root
#define CARD_FILE_NAME "ZNAX.DAT"

//the same name as a FAT directory entry holds it: eight characters then three, no dot,
//which is the form CHSd's fat::find takes
#define CARD_FILE_83 "ZNAX    DAT"

//every skin and picture name, hashed: a card made by another build has another stamp
#define CARD_STAMP 0x6211E7E3UL

//the sections of the container, by the name its table holds. Levels will be another one
#define CARD_SEC_IMAGES "IMGS"

//1 when any picture is kept as one colour a row, see FMT_ROWS. The game builds the
//code that draws one only then: a card without any is a game that need not carry it
#define CARD_HAS_ROWS 0

#define CARD_SKIN_COUNT 2
#define CARD_IMAGE_COUNT 22

//the skins, in the order the index holds them
enum CardSkin : uint8_t
{
	CARD_SKIN_DEFAULT = 0,
	CARD_SKIN_BLACK_WHITE = 1,
};

//what each skin is called on screen
#define CARD_SKIN_NAMES { "Default", "Black & white" }

//the pictures, in the order the index holds them within a skin
enum CardImage : uint8_t
{
	CARD_IMG_BACKGROUND = 0,
	CARD_IMG_BLOCKS = 1,
	CARD_IMG_CREDITS = 2,
	CARD_IMG_CREDITS1 = 3,
	CARD_IMG_CREDITS2 = 4,
	CARD_IMG_CURSOR = 5,
	CARD_IMG_FIXEDTIMER1 = 6,
	CARD_IMG_FIXEDTIMER2 = 7,
	CARD_IMG_GO = 8,
	CARD_IMG_HIGHSCORES = 9,
	CARD_IMG_HIGHSCORES1 = 10,
	CARD_IMG_HIGHSCORES2 = 11,
	CARD_IMG_INTRO1 = 12,
	CARD_IMG_INTRO2 = 13,
	CARD_IMG_PLAY1 = 14,
	CARD_IMG_PLAY2 = 15,
	CARD_IMG_READY = 16,
	CARD_IMG_RELATIVETIMER1 = 17,
	CARD_IMG_RELATIVETIMER2 = 18,
	CARD_IMG_SELECTGAME = 19,
	CARD_IMG_TIMEOVER = 20,
	CARD_IMG_TITLESCREEN = 21,
};
